version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: testtask-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: testtask
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: